########################################################################
# THIS FILE IS PART OF Planter PROJECT
# Copyright (c) Changgang Zheng and Computing Infrastructure Group
# Department of Engineering Science, University of Oxford
# All rights reserved.
# E-mail: changgang.zheng@eng.ox.ac.uk or changgangzheng@qq.com
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at :
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########################################################################
# This file was autogenerated

import json
import numpy as np
from scapy.all import *
from sklearn.metrics import *
from multiprocessing import *
from scipy.stats import pearsonr
import copy
import readline
import time
print('Predicted load table time ... (0.016s)')
time.sleep(0.016)
class Planter(Packet):
    name = 'Planter'
    fields_desc = [StrFixedLenField('P', 'P', length=1),
        StrFixedLenField('Four', '4', length=1),
        XByteField('version', 0x01),
        XByteField('type', 0x01),
        IntField('feature0', 0),
        IntField('feature1', 0),
        IntField('result', 0xDEADBABE)]

bind_layers(Ether, Planter, type=0x1234)

config_file = '/home/p4/Planter/src/configs/Planter_config.json'
num_components = 2
config_file = '/home/p4/Planter/src/temp/Test_Data.json'
Test_Data = json.load(open(config_file, 'r'))
sklearn_test_y = Test_Data['sklearn_test_y']
test_X = Test_Data['test_X']
test_y = Test_Data['test_y']

def send_receive_extract(pkt, iface, received_result0, received_result1):
    resp = srp1(pkt, iface=iface, timeout=1, verbose=False)
    if resp:
        receive_info = resp[Planter]
        if receive_info:
            received_result0.value = (int(receive_info.feature0))
            received_result1.value = (int(receive_info.feature1))
        else:
            print('\rCannot find Planter header in the {}th packet |'.format(i), end='')
    else:
        print('\rDid not receive response of the {}th packet |'.format(i), end='')

print("\n==============================================================================================")
print("=        Two steps to exit Planter: 1. input 'exit', press 'return'; 2. press ctrl + c       =")
print("==============================================================================================")
print('Test the switch model, the result should be the same as previous python test')
same = 0
correct = 0
error = 0
switch_test_y = []
sklearn_test_x = copy.deepcopy(sklearn_test_y)
switch_test_x = copy.deepcopy(sklearn_test_y)

for i in range(np.shape(test_X)[0]):
    iface = 'eth0'
    pkt = Ether(dst='00:04:00:00:00:00', type=0x1234) / Planter( feature0 = int(test_X[i][0]), feature1 = int(test_X[i][1]), result  = int(404))
    pkt = pkt/' '

    received_result0 = Manager().Value('i', 404)
    received_result1 = Manager().Value('i', 404)

    s_r_e = Process(target=send_receive_extract, args=(pkt,iface,received_result0,received_result1,))
    s_r_e.daemon = True
    s_r_e.start()
    s_r_e.join()

    switch_test_x[i][0] = received_result0.value
    switch_test_x[i][1] = received_result1.value
for ax in range(num_components):
    corr, _ = pearsonr(np.array(sklearn_test_x)[:, ax], np.array(switch_test_x)[:, ax])
    print('Pearsons correlation of M/A result and output of Pytorch for axis '+str(ax)+' is: %.3f' % corr)
print("======================================= Test Finished ========================================")
