########################################################################
# THIS FILE IS PART OF Planter PROJECT
# Copyright (c) Changgang Zheng and Computing Infrastructure Group
# Department of Engineering Science, University of Oxford
# All rights reserved.
# E-mail: changgang.zheng@eng.ox.ac.uk or changgangzheng@qq.com
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at :
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########################################################################
# This file was autogenerated

import json
import os
import binascii
import sys
sys.path.append('/home/p4/Planter')
os.chdir('/home/p4/Planter')
print('working dir: ' + os.getcwd())
table = json.load(open('./Tables/Exact_Table.json','r'))
Planter_config = json.load(open('./src/configs/Planter_config.json','r'))
config = Planter_config['p4 config']

Ingress = bfrt.Bayes_performance_Conveqs.pipe.SwitchIngress
Ingress.clear()

def ten_to_bin(num, count):
    num = bin(num).lstrip('0b')
    if len(num) != count:
        cont = count - len(num)
        num = cont * '0' + num
    return num

print('load feature 0 table with',len(table['feature 0'].keys()),'entries')
for k in range(len(table['feature 0'].keys())):
    key = str(k)
    Ingress.lookup_feature0.add_with_extract_feature0(int(key), table['feature 0'][key]['class 0'], table['feature 0'][key]['class 1'], table['feature 0'][key]['class 2'], table['feature 0'][key]['class 3'], table['feature 0'][key]['class 4'], table['feature 0'][key]['class 5'], table['feature 0'][key]['class 6'], table['feature 0'][key]['class 7'], table['feature 0'][key]['class 8'], table['feature 0'][key]['class 9'], table['feature 0'][key]['class 10'], table['feature 0'][key]['class 11'], table['feature 0'][key]['class 12'], table['feature 0'][key]['class 13'], table['feature 0'][key]['class 14'], table['feature 0'][key]['class 15'], table['feature 0'][key]['class 16'], table['feature 0'][key]['class 17'], table['feature 0'][key]['class 18'], table['feature 0'][key]['class 19'], table['feature 0'][key]['class 20'])

print('load feature 1 table with',len(table['feature 1'].keys()),'entries')
for k in range(len(table['feature 1'].keys())):
    key = str(k)
    Ingress.lookup_feature1.add_with_extract_feature1(int(key), table['feature 1'][key]['class 0'], table['feature 1'][key]['class 1'], table['feature 1'][key]['class 2'], table['feature 1'][key]['class 3'], table['feature 1'][key]['class 4'], table['feature 1'][key]['class 5'], table['feature 1'][key]['class 6'], table['feature 1'][key]['class 7'], table['feature 1'][key]['class 8'], table['feature 1'][key]['class 9'], table['feature 1'][key]['class 10'], table['feature 1'][key]['class 11'], table['feature 1'][key]['class 12'], table['feature 1'][key]['class 13'], table['feature 1'][key]['class 14'], table['feature 1'][key]['class 15'], table['feature 1'][key]['class 16'], table['feature 1'][key]['class 17'], table['feature 1'][key]['class 18'], table['feature 1'][key]['class 19'], table['feature 1'][key]['class 20'])

print('load feature 2 table with',len(table['feature 2'].keys()),'entries')
for k in range(len(table['feature 2'].keys())):
    key = str(k)
    Ingress.lookup_feature2.add_with_extract_feature2(int(key), table['feature 2'][key]['class 0'], table['feature 2'][key]['class 1'], table['feature 2'][key]['class 2'], table['feature 2'][key]['class 3'], table['feature 2'][key]['class 4'], table['feature 2'][key]['class 5'], table['feature 2'][key]['class 6'], table['feature 2'][key]['class 7'], table['feature 2'][key]['class 8'], table['feature 2'][key]['class 9'], table['feature 2'][key]['class 10'], table['feature 2'][key]['class 11'], table['feature 2'][key]['class 12'], table['feature 2'][key]['class 13'], table['feature 2'][key]['class 14'], table['feature 2'][key]['class 15'], table['feature 2'][key]['class 16'], table['feature 2'][key]['class 17'], table['feature 2'][key]['class 18'], table['feature 2'][key]['class 19'], table['feature 2'][key]['class 20'])

print('load feature 3 table with',len(table['feature 3'].keys()),'entries')
for k in range(len(table['feature 3'].keys())):
    key = str(k)
    Ingress.lookup_feature3.add_with_extract_feature3(int(key), table['feature 3'][key]['class 0'], table['feature 3'][key]['class 1'], table['feature 3'][key]['class 2'], table['feature 3'][key]['class 3'], table['feature 3'][key]['class 4'], table['feature 3'][key]['class 5'], table['feature 3'][key]['class 6'], table['feature 3'][key]['class 7'], table['feature 3'][key]['class 8'], table['feature 3'][key]['class 9'], table['feature 3'][key]['class 10'], table['feature 3'][key]['class 11'], table['feature 3'][key]['class 12'], table['feature 3'][key]['class 13'], table['feature 3'][key]['class 14'], table['feature 3'][key]['class 15'], table['feature 3'][key]['class 16'], table['feature 3'][key]['class 17'], table['feature 3'][key]['class 18'], table['feature 3'][key]['class 19'], table['feature 3'][key]['class 20'])

print('load feature 4 table with',len(table['feature 4'].keys()),'entries')
for k in range(len(table['feature 4'].keys())):
    key = str(k)
    Ingress.lookup_feature4.add_with_extract_feature4(int(key), table['feature 4'][key]['class 0'], table['feature 4'][key]['class 1'], table['feature 4'][key]['class 2'], table['feature 4'][key]['class 3'], table['feature 4'][key]['class 4'], table['feature 4'][key]['class 5'], table['feature 4'][key]['class 6'], table['feature 4'][key]['class 7'], table['feature 4'][key]['class 8'], table['feature 4'][key]['class 9'], table['feature 4'][key]['class 10'], table['feature 4'][key]['class 11'], table['feature 4'][key]['class 12'], table['feature 4'][key]['class 13'], table['feature 4'][key]['class 14'], table['feature 4'][key]['class 15'], table['feature 4'][key]['class 16'], table['feature 4'][key]['class 17'], table['feature 4'][key]['class 18'], table['feature 4'][key]['class 19'], table['feature 4'][key]['class 20'])

print('load feature 5 table with',len(table['feature 5'].keys()),'entries')
for k in range(len(table['feature 5'].keys())):
    key = str(k)
    Ingress.lookup_feature5.add_with_extract_feature5(int(key), table['feature 5'][key]['class 0'], table['feature 5'][key]['class 1'], table['feature 5'][key]['class 2'], table['feature 5'][key]['class 3'], table['feature 5'][key]['class 4'], table['feature 5'][key]['class 5'], table['feature 5'][key]['class 6'], table['feature 5'][key]['class 7'], table['feature 5'][key]['class 8'], table['feature 5'][key]['class 9'], table['feature 5'][key]['class 10'], table['feature 5'][key]['class 11'], table['feature 5'][key]['class 12'], table['feature 5'][key]['class 13'], table['feature 5'][key]['class 14'], table['feature 5'][key]['class 15'], table['feature 5'][key]['class 16'], table['feature 5'][key]['class 17'], table['feature 5'][key]['class 18'], table['feature 5'][key]['class 19'], table['feature 5'][key]['class 20'])

print('load feature 6 table with',len(table['feature 6'].keys()),'entries')
for k in range(len(table['feature 6'].keys())):
    key = str(k)
    Ingress.lookup_feature6.add_with_extract_feature6(int(key), table['feature 6'][key]['class 0'], table['feature 6'][key]['class 1'], table['feature 6'][key]['class 2'], table['feature 6'][key]['class 3'], table['feature 6'][key]['class 4'], table['feature 6'][key]['class 5'], table['feature 6'][key]['class 6'], table['feature 6'][key]['class 7'], table['feature 6'][key]['class 8'], table['feature 6'][key]['class 9'], table['feature 6'][key]['class 10'], table['feature 6'][key]['class 11'], table['feature 6'][key]['class 12'], table['feature 6'][key]['class 13'], table['feature 6'][key]['class 14'], table['feature 6'][key]['class 15'], table['feature 6'][key]['class 16'], table['feature 6'][key]['class 17'], table['feature 6'][key]['class 18'], table['feature 6'][key]['class 19'], table['feature 6'][key]['class 20'])

print('load feature 7 table with',len(table['feature 7'].keys()),'entries')
for k in range(len(table['feature 7'].keys())):
    key = str(k)
    Ingress.lookup_feature7.add_with_extract_feature7(int(key), table['feature 7'][key]['class 0'], table['feature 7'][key]['class 1'], table['feature 7'][key]['class 2'], table['feature 7'][key]['class 3'], table['feature 7'][key]['class 4'], table['feature 7'][key]['class 5'], table['feature 7'][key]['class 6'], table['feature 7'][key]['class 7'], table['feature 7'][key]['class 8'], table['feature 7'][key]['class 9'], table['feature 7'][key]['class 10'], table['feature 7'][key]['class 11'], table['feature 7'][key]['class 12'], table['feature 7'][key]['class 13'], table['feature 7'][key]['class 14'], table['feature 7'][key]['class 15'], table['feature 7'][key]['class 16'], table['feature 7'][key]['class 17'], table['feature 7'][key]['class 18'], table['feature 7'][key]['class 19'], table['feature 7'][key]['class 20'])

print('load thresh_and_bias table with 1 entries')
Ingress.class_prob.add_with_read_class_prob(1, table['class prob']['class 0'], table['class prob']['class 1'], table['class prob']['class 2'], table['class prob']['class 3'], table['class prob']['class 4'], table['class prob']['class 5'], table['class prob']['class 6'], table['class prob']['class 7'], table['class prob']['class 8'], table['class prob']['class 9'], table['class prob']['class 10'], table['class prob']['class 11'], table['class prob']['class 12'], table['class prob']['class 13'], table['class prob']['class 14'], table['class prob']['class 15'], table['class prob']['class 16'], table['class prob']['class 17'], table['class prob']['class 18'], table['class prob']['class 19'], table['class prob']['class 20'])

