########################################################################
# THIS FILE IS PART OF Planter PROJECT
# Copyright (c) Changgang Zheng and Computing Infrastructure Group
# Department of Engineering Science, University of Oxford
# All rights reserved.
# E-mail: changgang.zheng@eng.ox.ac.uk or changgangzheng@qq.com
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at :
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#########################################################################
# This file was autogenerated

/*
 * Planter
 *
 * This program implements a simple protocol. It can be carried over Ethernet
 * (Ethertype 0x1234).
 *
 * The Protocol header looks like this:
 *
 *        0                1                  2              3
 * +----------------+----------------+----------------+---------------+
 * |      P         |       4        |     Version    |     Type      |
 * +----------------+----------------+----------------+---------------+
 * |                              feature0                            |
 * +----------------+----------------+----------------+---------------+
 * |                              feature1                            |
 * +----------------+----------------+----------------+---------------+
 * |                              feature2                            |
 * +----------------+----------------+----------------+---------------+
 * |                              Result                              |
 * +----------------+----------------+----------------+---------------+
 *
 * P is an ASCII Letter 'P' (0x50)
 * 4 is an ASCII Letter '4' (0x34)
 * Version is currently 1 (0x01)
 * Type is currently 1 (0x01)
 *
 * The device receives a packet, do the classification, fills in the
 * result and sends the packet back out of the same port it came in on, while
 * swapping the source and destination addresses.
 *
 * If an unknown operation is specified or the header is not valid, the packet
 * is dropped
 */

#include <core.p4>
#include <v1model.p4>

/*************************************************************************
*********************** headers and metadata *****************************
*************************************************************************/

const bit<16> ETHERTYPE_Planter = 0x1234;
const bit<8>  Planter_P     = 0x50;   // 'P'
const bit<8>  Planter_4     = 0x34;   // '4'
const bit<8>  Planter_VER   = 0x01;   // v0.1

header ethernet_h {
    bit<48> dstAddr;
    bit<48> srcAddr;
    bit<16> etherType;
}

header Planter_h{
    bit<8> p;
    bit<8> four;
    bit<8> ver;
    bit<8> typ;
    bit<32> feature0;
    bit<32> feature1;
    bit<32> feature2;
    bit<32> result;
}

struct header_t {
    ethernet_h   ethernet;
    Planter_h    Planter;
}

struct metadata_t {
    bit<16> f0_hp0;
    bit<16> f0_hp1;
    bit<16> f0_hp2;
    bit<16> f0_hp3;
    bit<16> f0_hp4;
    bit<16> f0_hp5;
    bit<16> f1_hp0;
    bit<16> f1_hp1;
    bit<16> f1_hp2;
    bit<16> f1_hp3;
    bit<16> f1_hp4;
    bit<16> f1_hp5;
    bit<16> f2_hp0;
    bit<16> f2_hp1;
    bit<16> f2_hp2;
    bit<16> f2_hp3;
    bit<16> f2_hp4;
    bit<16> f2_hp5;
    bit<16> bias_hp0;
    bit<16> bias_hp1;
    bit<16> bias_hp2;
    bit<16> bias_hp3;
    bit<16> bias_hp4;
    bit<16> bias_hp5;
    bit<16> threshold_hp0;
    bit<16> threshold_hp1;
    bit<16> threshold_hp2;
    bit<16> threshold_hp3;
    bit<16> threshold_hp4;
    bit<16> threshold_hp5;
    bit<16> result_hp0;
    bit<16> result_hp1;
    bit<16> result_hp2;
    bit<16> result_hp3;
    bit<16> result_hp4;
    bit<16> result_hp5;
    bit<4> vote_c0;
    bit<4> vote_c1;
    bit<4> vote_c2;
    bit<4> vote_c3;
    bit<32> feature0;
    bit<32> feature1;
    bit<32> feature2;
    bit<32> result;
    bit<8> flag ;
}

/*************************************************************************
*********************** Ingress Parser ***********************************
*************************************************************************/

parser SwitchParser(
    packet_in pkt,
    out header_t hdr,
    inout metadata_t meta,
    inout standard_metadata_t ig_intr_md) {

    state start {
        transition parse_ethernet;
    }

    state parse_ethernet {
        pkt.extract(hdr.ethernet);
        transition select(hdr.ethernet.etherType) {
        ETHERTYPE_Planter : check_planter_version;
        default           : accept;
        }
    }

    state check_planter_version {
        transition select(pkt.lookahead<Planter_h>().p,
                          pkt.lookahead<Planter_h>().four,
                          pkt.lookahead<Planter_h>().ver) {
        (Planter_P, Planter_4, Planter_VER) : parse_planter;
        default                             : accept;
        }
    }

    state parse_planter {
        pkt.extract(hdr.Planter);
        meta.feature0 = hdr.Planter.feature0;
        meta.feature1 = hdr.Planter.feature1;
        meta.feature2 = hdr.Planter.feature2;
        meta.flag = 1 ;
        transition accept;
    }
}

/*************************************************************************
*********************** Egress Deparser *********************************
**************************************************************************/

control SwitchDeparser(
    packet_out pkt,
    in header_t hdr) {
    apply {
        pkt.emit(hdr);
    }
}

/*************************************************************************
********************** Checksum Verification *****************************
*************************************************************************/

control SwitchVerifyChecksum(inout header_t hdr,
                       inout metadata_t meta) {
    apply {}
}
/*************************************************************************
********************** Checksum Computation ******************************
*************************************************************************/

control SwitchComputeChecksum(inout header_t hdr,
                        inout metadata_t meta) {
    apply {}
}
/*************************************************************************
*********************** Ingress Processing********************************
**************************************************************************/

control SwitchIngress(
    inout header_t hdr,
    inout metadata_t meta,
    inout standard_metadata_t ig_intr_md) {

    action send(bit<9> port) {
        ig_intr_md.egress_spec = port;
    }

    action drop() {
        mark_to_drop(ig_intr_md);
    }

    action extract_feature0(bit<16> f0hp0, bit<16> f0hp1, bit<16> f0hp2, bit<16> f0hp3, bit<16> f0hp4, bit<16> f0hp5){
        meta.result_hp0 = meta.result_hp0 + f0hp0;
        meta.result_hp1 = meta.result_hp1 + f0hp1;
        meta.result_hp2 = meta.result_hp2 + f0hp2;
        meta.result_hp3 = meta.result_hp3 + f0hp3;
        meta.result_hp4 = meta.result_hp4 + f0hp4;
        meta.result_hp5 = meta.result_hp5 + f0hp5;
    }

    action extract_feature1(bit<16> f1hp0, bit<16> f1hp1, bit<16> f1hp2, bit<16> f1hp3, bit<16> f1hp4, bit<16> f1hp5){
        meta.result_hp0 = meta.result_hp0 + f1hp0;
        meta.result_hp1 = meta.result_hp1 + f1hp1;
        meta.result_hp2 = meta.result_hp2 + f1hp2;
        meta.result_hp3 = meta.result_hp3 + f1hp3;
        meta.result_hp4 = meta.result_hp4 + f1hp4;
        meta.result_hp5 = meta.result_hp5 + f1hp5;
    }

    action extract_feature2(bit<16> f2hp0, bit<16> f2hp1, bit<16> f2hp2, bit<16> f2hp3, bit<16> f2hp4, bit<16> f2hp5){
        meta.result_hp0 = meta.result_hp0 + f2hp0;
        meta.result_hp1 = meta.result_hp1 + f2hp1;
        meta.result_hp2 = meta.result_hp2 + f2hp2;
        meta.result_hp3 = meta.result_hp3 + f2hp3;
        meta.result_hp4 = meta.result_hp4 + f2hp4;
        meta.result_hp5 = meta.result_hp5 + f2hp5;
    }

    table lookup_feature0 {
        key = { meta.feature0:exact; }
        actions = {
            extract_feature0();
            NoAction;
            }
        size = 34101;
        default_action = NoAction;
    }

    table lookup_feature1 {
        key = { meta.feature1:exact; }
        actions = {
            extract_feature1();
            NoAction;
            }
        size = 17;
        default_action = NoAction;
    }

    table lookup_feature2 {
        key = { meta.feature2:exact; }
        actions = {
            extract_feature2();
            NoAction;
            }
        size = 324;
        default_action = NoAction;
    }

    action read_thresh_and_bias(bit<16> thresh_hp0, bit<16> thresh_hp1, bit<16> thresh_hp2, bit<16> thresh_hp3, bit<16> thresh_hp4, bit<16> thresh_hp5, bit<16> bia_hp0, bit<16> bia_hp1, bit<16> bia_hp2, bit<16> bia_hp3, bit<16> bia_hp4, bit<16> bia_hp5){
        meta.threshold_hp0 = thresh_hp0;
        meta.threshold_hp1 = thresh_hp1;
        meta.threshold_hp2 = thresh_hp2;
        meta.threshold_hp3 = thresh_hp3;
        meta.threshold_hp4 = thresh_hp4;
        meta.threshold_hp5 = thresh_hp5;
        meta.result_hp0 = bia_hp0;
        meta.result_hp1 = bia_hp1;
        meta.result_hp2 = bia_hp2;
        meta.result_hp3 = bia_hp3;
        meta.result_hp4 = bia_hp4;
        meta.result_hp5 = bia_hp5;
    }

    table thresh_and_bias {
        key = {meta.flag:exact;}
        actions={read_thresh_and_bias; NoAction;}
        default_action = NoAction;
        size = 1;
    }

    action read_lable(bit<32> label){
        meta.result = label;
    }

    table decision {
        key = {
            meta.vote_c0: exact;
            meta.vote_c1: exact;
            meta.vote_c2: exact;
            meta.vote_c3: exact;
        }
        actions={read_lable; NoAction;}
        default_action = NoAction;
        size = 4096;
    }

    apply{
        meta.vote_c0=0;
        meta.vote_c1=0;
        meta.vote_c2=0;
        meta.vote_c3=0;
        thresh_and_bias.apply();
        lookup_feature0.apply();
        lookup_feature1.apply();
        lookup_feature2.apply();
        meta.result_hp0 = meta.threshold_hp0 - meta.result_hp0;
        meta.result_hp1 = meta.threshold_hp1 - meta.result_hp1;
        meta.result_hp2 = meta.threshold_hp2 - meta.result_hp2;
        meta.result_hp3 = meta.threshold_hp3 - meta.result_hp3;
        meta.result_hp4 = meta.threshold_hp4 - meta.result_hp4;
        meta.result_hp5 = meta.threshold_hp5 - meta.result_hp5;
        if(meta.result_hp0 & 0b1000000000000000==0){
            meta.vote_c1 = meta.vote_c1+ 1;
        }else{meta.vote_c0 = meta.vote_c0+ 1;}

        if(meta.result_hp1 & 0b1000000000000000==0){
            meta.vote_c2 = meta.vote_c2+ 1;
        }else{meta.vote_c0 = meta.vote_c0+ 1;}

        if(meta.result_hp2 & 0b1000000000000000==0){
            meta.vote_c3 = meta.vote_c3+ 1;
        }else{meta.vote_c0 = meta.vote_c0+ 1;}

        if(meta.result_hp3 & 0b1000000000000000==0){
            meta.vote_c2 = meta.vote_c2+ 1;
        }else{meta.vote_c1 = meta.vote_c1+ 1;}

        if(meta.result_hp4 & 0b1000000000000000==0){
            meta.vote_c3 = meta.vote_c3+ 1;
        }else{meta.vote_c1 = meta.vote_c1+ 1;}

        if(meta.result_hp5 & 0b1000000000000000==0){
            meta.vote_c3 = meta.vote_c3+ 1;
        }else{meta.vote_c2 = meta.vote_c2+ 1;}

        decision.apply();
        send(ig_intr_md.ingress_port);
    }
}
/*************************************************************************
*********************** egress Processing********************************
**************************************************************************/

control SwitchEgress(inout header_t hdr,
    inout metadata_t meta,
    inout standard_metadata_t eg_intr_md) {
    apply {
    }
}
/*************************************************************************
***********************  S W I T C H  ************************************
*************************************************************************/

V1Switch(
    SwitchParser(),
    SwitchVerifyChecksum(),
    SwitchIngress(),
    SwitchEgress(),
    SwitchComputeChecksum(),
    SwitchDeparser()
) main;